AgathaChristieFanPage/Models/ApplicationDbContext.cs
using AgathaChristieFanPage.Models.Auth;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;


namespace AgathaChristieFanPage.Models
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext() : base("ACFanPage", throwIfV1Schema: false)
        {
            base.Configuration.ProxyCreationEnabled = false;
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }

        public DbSet<ImageModel> Images { get; set; }
        public DbSet<NovelModel> Novels { get; set; }
    }
}

AgathaChristieFanPage/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AgathaChristieFanPage.Models.Auth
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public string DisplayName { get; set; }
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }
}

AgathaChristieFanPage/Models/ImageModel.cs
using System.Runtime.Serialization;

namespace AgathaChristieFanPage.Models
{
    [DataContract(IsReference = true)]
    public class ImageModel
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string AltText { get; set; }
        [DataMember]
        public string ImageUrl { get; set; }
        [DataMember]
        public int NovelId { get; set; }
        public virtual NovelModel Novel { get; set; }
    }
}

AgathaChristieFanPage/Models/NovelModel.cs
using System.Collections.Generic;

namespace AgathaChristieFanPage.Models
{
    public class NovelModel
    {
        public NovelModel()
        {
            Images = new HashSet<ImageModel>();
        }

        public int Id { get; set; }
        public string NovelName { get; set; }
        public string PublishingYear { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string ThumbnailUrl { get; set; }
        public virtual IEnumerable<ImageModel> Images { get; set; }
    }
}

AgathaChristieFanPage/ViewModels/ReadingChecklist.cs
using System.Collections.Generic;

namespace AgathaChristieFanPage.ViewModels
{
    public class ReadingChecklist
    {
        public IEnumerable<ReadingChecklistItem> Novels { get; set; }
    }
}

AgathaChristieFanPage/ViewModels/ReadingChecklistItem.cs
namespace AgathaChristieFanPage.ViewModels
{
    public class ReadingChecklistItem
    {
        public string NovelName { get; set; }
        public int NovelId { get; set; }
        public string PublishingYear { get; set; }
        public string Category { get; set; }
        public string ThumbnailUrl { get; set; }
        public bool Read { get; set; }
        public bool Watched { get; set; }
        public bool OwnACopy { get; set; }
    }
}

AgathaChristieFanPage/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AgathaChristieFanPage.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("~/Views/Home.cshtml");
        }
    }
}

AgathaChristieFanPage/Controllers/ReadingChecklistController.cs
using AgathaChristieFanPage.ModelBuilders;
using AgathaChristieFanPage.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace AgathaChristieFanPage.Controllers
{
    public class ReadingChecklistController : Controller
    {
        private IReadingChecklistModelBuilder _modelBuilder;

        public ReadingChecklistController(IReadingChecklistModelBuilder modelBuilder)
        {
            _modelBuilder = modelBuilder;
        }

        public ActionResult Index()
        {
            ReadingChecklist model = _modelBuilder.BuildModel();

            return View("~/Views/ReadingChecklist.cshtml", model);
        }
    }
}

AgathaChristieFanPage/Views/Home.cshtml
@Html.Action("Index", "ReadingChecklist")

AgathaChristieFanPage/Views/MasterLayout.cshtml
@using Microsoft.AspNet.Identity
@using AgathaChristieFanPage.Helpers;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Agatha Christie Fan Page">
    <title>Agatha Christie Fan Page</title>
    <link rel="shortcut icon" href="~/Styles/images/site-logo-icon.png">
    <link href='https://fonts.googleapis.com/css?family=Black+Ops+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
    @Styles.Render("~/bundle/styles")
    @Scripts.Render("~/bundle/angular")
</head>
<body ng-app="ACFanPage">
    <header ng-controller="NavigationController">
        <section class="logo-section">
            <a href='@Url.Action("Index", "Home")'>
                <img class ="logo" src='@Url.Content("~/Styles/images/site-logo.png")' />
            </a>
            <div class="user-info">
                @if (Request.IsAuthenticated)
                {
                    <p>Logged in as @CurrentUser.GetDisplayName()!</p>
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="(Log Out)" />
                    }
                }
                else
                {
                    @Html.ActionLink("Log In/Sign Up", "Login", "Account")
                }
            </div>
        </section>
        <nav>
            <ul>
                <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                <li><a href="#">ABOUT</a></li>
                <li></li>
                <li><a href="#">QUIZ</a></li>
                <li><a href="#">CONTACT US</a></li>
            </ul>
            <button ng-class="{'menu-open': IsMenuDrawerOpen}" class="burger-menu" ng-click="OpenMenuDrawer()"></button>
        </nav>
        <section>
            <div class="menu-drawer" menu-drawer-directive>
                <ul>
                    <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                    <li><a href="#">ABOUT</a></li>
                    <li><a href="#">QUIZ</a></li>
                    <li>
                        @if (Request.IsAuthenticated)
                        {
                            @Html.ActionLink("Logged in as " + User.Identity.GetUserName() + "!", "Index", "Manage")
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="submit" value="LOG OUT" />
                            }
                        }
                        else
                        {
                            @Html.ActionLink("LOG IN/SIGN UP", "Login", "Account")
                        }
                    </li>
                </ul>
            </div>
        </section>
    </header>
    <section class="header-image"></section>
    <section class="body-content">
        @RenderBody()
    </section>
    <footer>
        <span>Author: Anna Schechter</span>
    </footer>
</body>
</html>

AgathaChristieFanPage/Views/ReadingChecklist.cshtml
@model AgathaChristieFanPage.ViewModels.ReadingChecklist

@{ Layout = ""; }
<script>
    window.app.value('novelsData', @Html.Raw(@Json.Encode(Model.Novels)));
</script>

@Html.Partial("~/Views/_PageTitlePartial.cshtml", null, new ViewDataDictionary { { "PageTitle", "READING CHECKLIST" } })

<article class="reading-checklist" ng-controller="ReadingChecklistController">
    <table>
        <tr ng-repeat="novel in Novels" checklist-item-directive class="checklist-item">
            <td class="thumbnail-cell" ng-click="ShowNovelDetails(novel.NovelId)">
                <img class="thumbnail" ng-src="{{::novel.ThumbnailUrl}}" />
            </td>
            <td class="novel-name-cell" ng-click="ShowNovelDetails(novel.NovelId)">{{::novel.NovelName}}</td>
            <td class="publishing-year-cell">Published in {{::novel.PublishingYear}}</td>
            <td class="category-cell">{{::novel.Category}}</td>
            <td class="checkbox-cell">
                <div>
                    <input id="read-{{::novel.NovelName}}" type="checkbox" ng-model="novel.Read">
                    <label for="read-{{::novel.NovelName}}">Read</label>
                </div>
                <div>
                    <input id="watched-{{::novel.NovelName}}" type="checkbox" ng-model="novel.Watched">
                    <label for="watched-{{::novel.NovelName}}">Watched</label>
                </div>
                <div>
                    <input id="ownACopy-{{::novel.NovelName}}" type="checkbox" ng-model="novel.OwnACopy">
                    <label for="ownACopy-{{::novel.NovelName}}">Own a Copy</label>
                </div>
            </td>
        </tr>
    </table>
    <div class="checklist-summary">
        <h4>This is your checklist summary. Out of all novels ever written by Agatha Christie you have:</h4>
        <div class="filter">
            <div class="filter-icon" style="background-image: url('/Styles/images/read-icon.png')"></div>
            Read: {{(Novels | filter:{ Read: 'true'}).length}}/{{Novels.length}}
            <progress max="{{Novels.length}}" value="{{(Novels | filter:{ Read: 'true'}).length}}"></progress>
        </div>
        <div class="filter">
            <div class="filter-icon" style="background-image: url('/Styles/images/watched-icon.png')"></div>
            Watched: {{(Novels | filter:{ Watched: 'true'}).length}}/{{Novels.length}}
            <progress max="{{Novels.length}}" value="{{(Novels | filter:{ Watched: 'true'}).length}}"></progress>
        </div>
        <div class="filter">
            <div class="filter-icon" style="background-image: url('/Styles/images/own-a-copy-icon.png')"></div>
            Own A Copy: {{(Novels | filter:{ OwnACopy: 'true'}).length}}/{{Novels.length}}
            <progress max="{{Novels.length}}" value="{{(Novels | filter:{ OwnACopy: 'true'}).length}}"></progress>
        </div>
    </div>

    @Html.Partial("~/Views/_NovelDetailsPartial.cshtml")
</article>

AgathaChristieFanPage/Views/_NovelDetailsPartial.cshtml
<div class="novel-details-overlay" ng-controller="NovelDetailsController" ng-show="IsDisplaying">
    <button class="overlay-close-button" ng-click="CloseOverlay()"></button>
    <div class="overlay-content">
        <h2>{{Novel.NovelName}}</h2>
        <div class="image-carousel">
            <img ng-src="{{Novel.Images[0].ImageUrl}}" />
            <button class="arrow previous" ng-show="ActiveImageId !== 1" ng-click="PreviousImage()">&#10094;</button>
            <button class="arrow next" ng-show="ActiveImageId !== Novel.Images.length" ng-click="NextImage()">&#10095;</button>
            <ul class="carousel-images">
                <li ng-repeat="image in Novel.Images" carousel-image-directive="{{image.Id}}" active-image-id="{{ActiveImageId}}">
                    <img ng-src="{{image.ImageUrl}}" />
                </li>
            </ul>
        </div>
        <div class="novel-details">
            <h4>{{Novel.Category === "Other" ? "" : Novel.Category}} <span>(Published in {{Novel.PublishingYear}})</span></h4>
            <p>{{Novel.Description}}</p>
        </div>
    </div>
</div>

AgathaChristieFanPage/Views/_PageTitlePartial.cshtml
<div class="page-title">
    <div class="hor-line"><span></span></div>
    <h1>@this.ViewData["PageTitle"].ToString()</h1>
    <div class="hor-line"><span></span></div>
</div>